# Generated by Django 5.2.8 on 2025-11-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.CharField()),
            ],
        ),
    ]
