# Generated by Django 5.2.8 on 2025-11-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_Site', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pagina/')),
                ('texto_chamada', models.CharField(max_length=255)),
                ('texto_sobre', models.CharField(max_length=255)),
                ('imagem_sobre', models.ImageField(blank=True, null=True, upload_to='pagina/')),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.IntegerField()),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
